### ISSUE TITLE
Add configuration for semantic release

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-extension-seed#30]

**Comment by jessiehuff** [comment]
Related to https://github.com/patternfly/patternfly-extension-seed/issues/3

**Comment by dgutride** [comment]
If we do add configuration, we shouldn't run it though (so #3 should be closed in my opinion).

**Comment by wise-king-sullyman** [comment]
I think it would be beneficial for us to have the automated release process running here even if we won't actually use the package, as that would make it a lot easier for us to identify if any issues with the process come up before they actually impact consumers.

**Comment by dgutride** [comment]
Adding a package that is created from this might send the message that the npm package is what people should use.  Since you'd want to validate any of those assumptions before merging a PR, I don't quite see how releasing on merge would provide value.  It only will tell you after your code is in main that there is something wrong with it.  A seed validation process could be useful, but that would be outside of this repo (or as a separate package within it that runs some validation process after generation).
